
version: '3.8'

networks:
  f1net:
    driver: overlay

volumes:
  prom_data: {}
  graf_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=6h
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prom_data:/prometheus
    networks:
      - f1net
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      resources:
        limits: { cpus: '0.50', memory: 512M }

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - graf_data:/var/lib/grafana
    networks:
      - f1net
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      resources:
        limits: { cpus: '0.50', memory: 512M }

  telemetry-sim:
    build: ./telemetry-sim
    image: ghcr.io/vemavamsi/telemetry-sim:latest
    environment:
      - DRIVERS=20
      - UPDATE_INTERVAL=0.5
      - JITTER=0.2
    networks:
      - f1net
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      resources:
        limits: { cpus: '0.50', memory: 256M }
